### ISSUE TITLE
need to note SlicerRT dependency

### ISSUE THREAD

**Issue by pieper** [gsi-biomotion/SlicerRegistrationQA#8]
The installation instructions should mention that SlicerRT is a prerequisite for a local build.

**Comment by gsi-kanderle** [comment]
You are right, thanks, I'll amend that.

The SlicerRT functionality is only needed in one function. I could probably change the module, that it still builds if no SlicerRT is given, but the functionality is than reduced. Unfortunately, I don't know exactly how to do that.
How can I relay the information from Cmake to Module logic if a library (SegmentComparison) is available or not?

On 8 Mar 2018 9:03 p.m., Steve Pieper <notifications@github.com> wrote:

The installation instructions should mention that SlicerRT is a prerequisite for a local build.

**Comment by pieper** [comment]
Hi - 

Maybe the easiest is to have a variable like USE_SLICERRT and then only include the subdirectory with the dependency in an if clause in cmake.

https://github.com/gsi-biomotion/SlicerRegistrationQA/blob/master/CMakeLists.txt#L50-L54

Or in general if you want to pass data from cmake to c++ you can have a config.h.in file that then cmake can configure so that any variable in cmake can be exposed as a C++ definition you can use for ifdef.  

Something like this file:

https://github.com/Slicer/Slicer/blob/master/Base/Logic/vtkSlicerBaseLogicConfigure.h.in

Which is then configured into the build directory like this:

https://github.com/Slicer/Slicer/blob/master/Base/Logic/CMakeLists.txt#L88-L95

Be sure also to add the build directory to the include paths:

https://github.com/Slicer/Slicer/blob/master/Base/Logic/CMakeLists.txt#L56

Or another option would be not to add the subdirectory that includes the dependency if the cmake variable is not set.

HTH,
Steve

**Comment by gsi-kanderle** [comment]
Thanks, this is helpful.
I've added the SlicerRT requirement in the installation instructions. Now I'll try to make the build available with or without SlicerRT.

**Comment by pieper** [comment]
Looks great - thanks
